import { UpgradeSet, Upgrade, Divider, ObjectiveCard, Ship } from '../interfaces/cards'

type UpgradeCards = {
  [key in UpgradeSet]: Upgrade[] | Divider
}
const upgradeCards: UpgradeCards = {
  title: [
    {
      id: 1237,
      title: 'Admonition',
      image: 'admonition.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc30c-frigate': true,
      },
    },
    {
      id: 1010,
      title: 'Aspiration',
      image: 'aspiration.jpg',
      set: 'title',
      points: 3,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc75-cruiser': true,
      },
    },
    {
      id: 1326,
      title: 'Bright Hope',
      image: 'bright-hope.jpg',
      set: 'title',
      points: 2,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'gr-75': true,
      },
    },
    {
      id: 1239,
      title: 'Defiance',
      image: 'defiance.jpg',
      set: 'title',
      points: 5,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-cruiser': true,
      },
    },
    {
      id: 1110,
      title: "Dodonna's Pride",
      image: 'dodonnas-pride.jpg',
      set: 'title',
      points: 6,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        corvette: true,
      },
    },
    {
      id: 1327,
      title: 'Endeavor',
      image: 'endeavor.jpg',
      set: 'title',
      points: 4,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-liberty': true,
      },
    },
    {
      id: 1238,
      title: 'Foresight',
      image: 'foresight.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc30c-frigate': true,
      },
    },
    {
      id: 1116,
      title: 'Gallant Haven',
      image: 'gallant-haven.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'assault-frigate': true,
      },
    },
    {
      id: 2788,
      title: "Garel's Honor",
      image: 'swm27-garels-honor.jpg',
      set: 'title',
      points: 4,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        hammerhead: true,
      },
    },
    {
      id: 1240,
      title: 'Home One',
      image: 'home-one.jpg',
      set: 'title',
      points: 7,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-cruiser': true,
      },
    },
    {
      id: 1241,
      title: 'Independence',
      image: 'independence.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-cruiser': true,
      },
    },
    {
      id: 1111,
      title: "Jaina's Light",
      image: 'jainas-light.jpg',
      set: 'title',
      points: 2,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        corvette: true,
      },
    },
    {
      id: 1328,
      title: 'Liberty',
      image: 'liberty.jpg',
      set: 'title',
      points: 3,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-liberty': true,
      },
    },
    {
      id: 1329,
      title: 'Mon Karren',
      image: 'mon-karren.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc80-liberty': true,
      },
    },
    {
      id: 1117,
      title: 'Paragon',
      image: 'paragon.jpg',
      set: 'title',
      points: 5,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'assault-frigate': true,
      },
    },
    {
      id: 1401,
      title: 'Phoenix Home',
      image: 'phoenix-home.jpg',
      set: 'title',
      points: 3,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        pelta: true,
      },
    },
    {
      id: 1281,
      title: 'Profundity',
      image: 'profundity.jpg',
      set: 'title',
      points: 7,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'mc75-cruiser': true,
      },
    },
    {
      id: 1325,
      title: 'Quantum Storm',
      image: 'quantum-storm.jpg',
      set: 'title',
      points: 1,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'gr-75': true,
      },
    },
    {
      id: 1113,
      title: 'Redemption',
      image: 'redemption.jpg',
      set: 'title',
      points: 8,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'nebulon-b': true,
      },
    },
    {
      id: 1114,
      title: 'Salvation',
      image: 'salvation.jpg',
      set: 'title',
      points: 7,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'nebulon-b': true,
      },
    },
    {
      id: 1112,
      title: 'Tantive IV',
      image: 'tantive-iv.jpg',
      set: 'title',
      points: 3,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        corvette: true,
      },
    },
    {
      id: 1115,
      title: 'Yavaris',
      image: 'yavaris.jpg',
      set: 'title',
      points: 5,
      faction: 'rebel',
      unique: true,
      shipsAllowedOn: {
        'nebulon-b': true,
      },
    },
    {
      id: 1001,
      title: 'Mon Calamari Exodus Fleet',
      image: 'mon-calamari-exodus-fleet.jpg',
      set: 'title',
      points: 5,
      faction: 'rebel',
      shipsAllowedOn: {
        'mc30c-frigate': true,
        'mc75-cruiser': true,
        'mc80-cruiser': true,
        'mc80-liberty': true,
      },
    },
    {
      id: 2787,
      title: 'Task Force Antilles',
      image: 'swm27-task-force-antilles.jpg',
      set: 'title',
      points: 3,
      faction: 'rebel',
      shipsAllowedOn: { hammerhead: true },
    },
    {
      id: 2786,
      title: 'Task Force Organa',
      image: 'swm27-task-force-organa.jpg',
      set: 'title',
      points: 1,
      faction: 'rebel',
      shipsAllowedOn: { hammerhead: true },
    },
    {
      id: 1232,
      title: 'Avenger',
      image: 'avenger.jpg',
      set: 'title',
      points: 5,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'imperial-class-star-destroyer': true,
      },
    },
    {
      id: 1391,
      title: 'Centicore',
      image: 'centicore.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        arquitens: true,
      },
    },
    {
      id: 1280,
      title: 'Chimaera',
      image: 'chimaera.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'imperial-class-star-destroyer': true,
      },
    },
    {
      id: 1107,
      title: 'Corrupter',
      image: 'corrupter.jpg',
      set: 'title',
      points: 5,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'victory-class-star-destroyer': true,
      },
    },
    {
      id: 1233,
      title: 'Devastator',
      image: 'devastator.jpg',
      set: 'title',
      points: 10,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'imperial-class-star-destroyer': true,
      },
    },
    {
      id: 1118,
      title: 'Demolisher',
      image: 'demolisher.jpg',
      set: 'title',
      points: 10,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'gladiator-class-star-destroyer': true,
      },
    },
    {
      id: 1108,
      title: 'Dominator',
      image: 'dominator.jpg',
      set: 'title',
      points: 12,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'victory-class-star-destroyer': true,
      },
    },
    {
      id: 1397,
      title: 'Hand of Justice',
      image: 'hand-of-justice.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        arquitens: true,
      },
    },
    {
      id: 1235,
      title: 'Impetuous',
      image: 'impetuous.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'raider-class-corvette': true,
      },
    },
    {
      id: 1119,
      title: 'Insidious',
      image: 'insidious.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'gladiator-class-star-destroyer': true,
      },
    },
    {
      id: 1236,
      title: 'Instigator',
      image: 'instigator.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'raider-class-corvette': true,
      },
    },
    {
      id: 1324,
      title: 'Interdictor',
      image: 'interdictor.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        interdictor: true,
      },
    },
    {
      id: 2667,
      title: 'Pursuant',
      image: 'pursuant.jpg',
      set: 'title',
      points: 2,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        quasar: true,
      },
    },
    {
      id: 1234,
      title: 'Relentless',
      image: 'relentless.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'imperial-class-star-destroyer': true,
      },
    },
    {
      id: 1011,
      title: 'Sovereign',
      image: 'sovereign.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'imperial-class-star-destroyer': true,
      },
    },
    {
      id: 2668,
      title: 'Squall',
      image: 'squall.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        quasar: true,
      },
    },
    {
      id: 2669,
      title: 'Stronghold',
      image: 'stronghold.jpg',
      set: 'title',
      points: 5,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        quasar: true,
      },
    },
    {
      id: 1323,
      title: 'Suppressor',
      image: 'suppressor.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        gozanti: true,
      },
    },
    {
      id: 1322,
      title: 'Vector',
      image: 'vector.jpg',
      set: 'title',
      points: 2,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        gozanti: true,
      },
    },
    {
      id: 1109,
      title: 'Warlord',
      image: 'warlord.jpg',
      set: 'title',
      points: 8,
      faction: 'imperial',
      unique: true,
      shipsAllowedOn: {
        'victory-class-star-destroyer': true,
      },
    },
    {
      id: 1007,
      title: 'Seventh Fleet Star Destroyer',
      image: 'seventh-fleet.jpg',
      set: 'title',
      points: 5,
      faction: 'imperial',
      shipsAllowedOn: {
        'gladiator-class-star-destroyer': true,
        'imperial-class-star-destroyer': true,
        'victory-class-star-destroyer': true,
        'super-star-destroyer': true,
      },
    },
    {
      id: 121213,
      title: 'Annihilator',
      image: 'annihilator.jpg',
      set: 'title',
      points: 8,
      faction: 'imperial',
      shipsAllowedOn: {
        'super-star-destroyer': true,
      },
    },
    {
      id: 1212134663,
      title: 'Eclipse',
      image: 'eclipse.jpg',
      set: 'title',
      points: 3,
      faction: 'imperial',
      shipsAllowedOn: {
        'super-star-destroyer': true,
      },
    },
    {
      id: 1444663,
      title: 'Executor',
      image: 'executor.jpg',
      set: 'title',
      points: 2,
      faction: 'imperial',
      shipsAllowedOn: {
        'super-star-destroyer': true,
      },
    },
    {
      id: 177745743,
      title: 'Ravager',
      image: 'ravager.jpg',
      set: 'title',
      points: 4,
      faction: 'imperial',
      shipsAllowedOn: {
        'super-star-destroyer': true,
      },
    },
  ],
  turbolasers: [
    {
      id: 1394,
      title: 'Dual Turbolaser Turrets',
      image: 'dual-turbolaser-turrets.jpg',
      set: 'turbolasers',
      points: 5,
      modification: true,
    },
    {
      id: 1095,
      title: 'Enhanced Armament',
      image: 'enhanced-armament.jpg',
      set: 'turbolasers',
      points: 10,
      modification: true,
    },
    {
      id: 1096,
      title: 'H9 Turbolasers',
      image: 'h9-turbolasers.jpg',
      set: 'turbolasers',
      points: 8,
    },
    {
      id: 1220,
      title: 'Heavy Turbolaser Turrets',
      image: 'heavy-turbolaser-turrets.jpg',
      set: 'turbolasers',
      points: 6,
    },
    {
      id: 3137,
      title: 'Quad Battery Turrets',
      image: 'quad-battery-turrets.jpg',
      set: 'turbolasers',
      points: 5,
      modification: true,
    },
    {
      id: 1319,
      title: 'Quad Turbolaser Cannons',
      image: 'quad-turbolaser-cannons.jpg',
      set: 'turbolasers',
      points: 10,
    },
    {
      id: 1229,
      title: 'Slaved Turrets',
      image: 'slaved-turrets.jpg',
      set: 'turbolasers',
      points: 6,
      modification: true,
    },
    {
      id: 1318,
      title: 'Spinal Armament',
      image: 'spinal-armament.jpg',
      set: 'turbolasers',
      points: 9,
      modification: true,
    },
    {
      id: 1221,
      title: 'Turbolaser Reroute Circuits',
      image: 'turbolaser-reroute-circuits.jpg',
      set: 'turbolasers',
      points: 7,
    },
    {
      id: 1097,
      title: 'XI7 Turbolasers',
      image: 'xi7-turbolasers.jpg',
      set: 'turbolasers',
      points: 6,
    },
    {
      id: 1098,
      title: 'XX-9 Turbolasers',
      image: 'xx9-turbolasers.jpg',
      set: 'turbolasers',
      points: 5,
    },
  ],
  'ion-cannons': [
    {
      id: 1020,
      title: 'Heavy Ion Emplacements',
      image: 'heavy-ion-emplacements.jpg',
      set: 'ion-cannons',
      points: 9,
    },
    {
      id: 1321,
      title: 'High-Capacity Ion Turbines',
      image: 'high-capacity-ion-turbines.jpg',
      set: 'ion-cannons',
      points: 8,
      modification: true,
    },
    {
      id: 1099,
      title: 'Ion Cannon Batteries',
      image: 'ion-cannon-batteries.jpg',
      set: 'ion-cannons',
      points: 5,
    },
    {
      id: 1100,
      title: 'Leading Shots',
      image: 'leading-shots.jpg',
      set: 'ion-cannons',
      points: 4,
    },
    {
      id: 1320,
      title: 'MS-1 Ion Cannons',
      image: 'ms-1-ion-cannons.jpg',
      set: 'ion-cannons',
      points: 2,
    },
    {
      id: 1272,
      title: 'NK-7 Ion Cannons',
      image: 'nk-7-ion-cannons.jpg',
      set: 'ion-cannons',
      points: 10,
    },
    {
      id: 1101,
      title: 'Overload Pulse',
      image: 'overload-pulse.jpg',
      set: 'ion-cannons',
      points: 8,
    },
    {
      id: 1222,
      title: 'SW-7 Ion Batteries',
      image: 'sw-7-ion-batteries.jpg',
      set: 'ion-cannons',
      points: 5,
    },
  ],
  ordnance: [
    {
      id: 1102,
      title: 'Assault Concussion Missiles',
      image: 'assault-concussion-missiles.jpg',
      set: 'ordnance',
      points: 7,
    },
    {
      id: 1223,
      title: 'Assault Proton Torpedoes',
      image: 'assault-proton-torpedoes.jpg',
      set: 'ordnance',
      points: 5,
    },
    {
      id: 1103,
      title: 'Expanded Launchers',
      image: 'expanded-launchers.jpg',
      set: 'ordnance',
      points: 13,
      modification: true,
    },
    {
      id: 2789,
      title: 'External Racks',
      image: 'external-racks.jpg',
      set: 'ordnance',
      points: 3,
    },
    {
      id: 1396,
      title: 'Flechette Torpedoes',
      image: 'flechette-torpedoes.jpg',
      set: 'ordnance',
      points: 3,
    },
    {
      id: 1021,
      title: 'Ordnance Pods',
      image: 'ordnance-pods.jpg',
      set: 'ordnance',
      points: 3,
    },
    {
      id: 1224,
      title: 'Rapid Reload',
      image: 'rapid-reload.jpg',
      set: 'ordnance',
      points: 8,
      modification: true,
    },
    {
      id: 1004,
      title: 'Wide-Area Barrage',
      image: 'wide-area-barrage.jpg',
      set: 'ordnance',
      points: 2,
    },
  ],
  'experimental-retrofit': [
    {
      id: 1300,
      title: 'G-8 Experimental Projector',
      image: 'g-8_experimental_projector.jpg',
      set: 'experimental-retrofit',
      points: 8,
      unique: true,
    },
    {
      id: 1302,
      title: 'Grav Shift Reroute',
      image: 'grav-shift-reroute.jpg',
      set: 'experimental-retrofit',
      points: 2,
      unique: true,
    },
    {
      id: 1299,
      title: 'G7-X Grav Well Projector',
      image: 'g7_x_grav_well_projector.jpg',
      set: 'experimental-retrofit',
      points: 2,
    },
    {
      id: 1301,
      title: 'Targeting Scrambler',
      image: 'targeting-scrambler.jpg',
      set: 'experimental-retrofit',
      points: 5,
    },
  ],
  'defensive-retrofit': [
    {
      id: 1093,
      title: 'Advanced Projectors',
      image: 'advanced-projectors.jpg',
      set: 'defensive-retrofit',
      points: 6,
    },
    {
      id: 1218,
      title: 'Cluster Bombs',
      image: 'cluster-bombs.jpg',
      set: 'defensive-retrofit',
      points: 5,
    },
    {
      id: 1018,
      title: 'Early Warning System',
      image: 'early-warning-system.jpg',
      set: 'defensive-retrofit',
      points: 7,
    },
    {
      id: 1094,
      title: 'Electronic Countermeasures',
      image: 'electronic-countermeasures.jpg',
      set: 'defensive-retrofit',
      points: 7,
    },
    {
      id: 1219,
      title: 'Redundant Shields',
      image: 'redundant-shields.jpg',
      set: 'defensive-retrofit',
      points: 8,
      modification: true,
    },
    {
      id: 1403,
      title: 'Reinforced Blast Doors',
      image: 'reinforced-blast-doors.jpg',
      set: 'defensive-retrofit',
      points: 5,
    },
  ],
  'offensive-retrofit': [
    {
      id: 1230,
      title: 'Boosted Comms',
      image: 'boosted-comms.jpg',
      set: 'offensive-retrofit',
      points: 4,
    },
    {
      id: 2673,
      title: 'Disposable Capacitors',
      image: 'disposable-capacitors.jpg',
      set: 'offensive-retrofit',
      points: 3,
    },
    {
      id: 1091,
      title: 'Expanded Hangar Bay',
      image: 'expanded-hangar-bay.jpg',
      set: 'offensive-retrofit',
      points: 5,
    },
    {
      id: 1019,
      title: 'Hardend Bulkheads',
      image: 'hardend-bulkheads.jpg',
      set: 'offensive-retrofit',
      points: 5,
    },
    {
      id: 1212,
      title: 'Phylon Q7 Tractor Beams',
      image: 'phylon-q7-tractor-beams.jpg',
      set: 'offensive-retrofit',
      points: 6,
      modification: true,
    },
    {
      id: 1092,
      title: 'Point-Defense Reroute',
      image: 'point-defense-reroute.jpg',
      set: 'offensive-retrofit',
      points: 5,
    },
    {
      id: 1214,
      title: 'Quad Laser Turrets',
      image: 'quad-laser-turrets.jpg',
      set: 'offensive-retrofit',
      points: 5,
    },
    {
      id: 1402,
      title: 'Rapid Launch Bays',
      image: 'rapid-launch-bays.jpg',
      set: 'offensive-retrofit',
      points: 6,
    },
    {
      divider: true,
    },
    {
      id: 2790,
      title: 'Cham Syndulla',
      image: 'cham-syndulla.jpg',
      set: 'offensive-retrofit',
      points: 5,
      faction: 'rebel',
      unique: true,
      dual: 'weapons-team',
    },
    {
      id: 1005,
      title: 'Jyn Erso',
      image: 'jyn-erso.jpg',
      set: 'offensive-retrofit',
      points: 4,
      faction: 'rebel',
      unique: true,
      dual: 'weapons-team',
    },
    {
      id: 1013,
      title: 'Darth Vader',
      image: 'darth-vader.jpg',
      set: 'offensive-retrofit',
      points: 3,
      faction: 'imperial',
      unique: true,
      dual: 'weapons-team',
    },
    {
      id: 2052,
      title: 'Boarding Engineers',
      image: 'boarding-engineers.jpg',
      set: 'offensive-retrofit',
      points: 2,
      dual: 'weapons-team',
    },
    {
      id: 2053,
      title: 'Boarding Troopers',
      image: 'boarding-troopers.jpg',
      set: 'offensive-retrofit',
      points: 3,
      dual: 'weapons-team',
    },
  ],
  'weapons-team': [
    {
      id: 1006,
      title: 'Caitken and Shollan',
      image: 'caitken-and-shollan.jpg',
      set: 'weapons-team',
      points: 6,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1315,
      title: 'Fire-Control Team',
      image: 'fire-control-team.jpg',
      set: 'weapons-team',
      points: 2,
    },
    {
      id: 1085,
      title: 'Flight Controllers',
      image: 'flight-controllers.jpg',
      set: 'weapons-team',
      points: 6,
    },
    {
      id: 1086,
      title: 'Gunnery Team',
      image: 'gunnery-team.jpg',
      set: 'weapons-team',
      points: 7,
    },
    {
      id: 1211,
      title: 'Ordnance Experts',
      image: 'ordnance-experts.jpg',
      set: 'weapons-team',
      points: 4,
    },
    {
      id: 1210,
      title: 'Ruthless Strategists',
      image: 'ruthless-strategists.jpg',
      set: 'weapons-team',
      points: 4,
    },
    {
      id: 1087,
      title: 'Sensor Team',
      image: 'sensor-team.jpg',
      set: 'weapons-team',
      points: 5,
    },
    {
      id: 1314,
      title: 'Veteran Gunners',
      image: 'veteran-gunners.jpg',
      set: 'weapons-team',
      points: 5,
    },
    {
      divider: true,
    },
    {
      id: 2790,
      title: 'Cham Syndulla',
      image: 'cham-syndulla.jpg',
      set: 'weapons-team',
      points: 5,
      faction: 'rebel',
      unique: true,
      dual: 'offensive-retrofit',
    },
    {
      id: 1005,
      title: 'Jyn Erso',
      image: 'jyn-erso.jpg',
      set: 'weapons-team',
      points: 4,
      faction: 'rebel',
      unique: true,
      dual: 'offensive-retrofit',
    },
    {
      id: 1013,
      title: 'Darth Vader',
      image: 'darth-vader.jpg',
      set: 'weapons-team',
      points: 3,
      faction: 'imperial',
      unique: true,
      dual: 'offensive-retrofit',
    },
    {
      id: 2052,
      title: 'Boarding Engineers',
      image: 'boarding-engineers.jpg',
      set: 'weapons-team',
      points: 2,
      dual: 'offensive-retrofit',
    },
    {
      id: 2053,
      title: 'Boarding Troopers',
      image: 'boarding-troopers.jpg',
      set: 'weapons-team',
      points: 3,
      dual: 'offensive-retrofit',
    },
  ],
  'fleet-support': [
    {
      id: 1294,
      title: 'Bomber Command Center',
      image: 'bomber-command-center.jpg',
      set: 'fleet-support',
      points: 8,
    },
    {
      id: 1295,
      title: 'Comms Net',
      image: 'comms-net.jpg',
      set: 'fleet-support',
      points: 2,
    },
    {
      id: 1298,
      title: 'Jamming Field',
      image: 'jamming-field.jpg',
      set: 'fleet-support',
      points: 2,
    },
    {
      id: 1296,
      title: 'Repair Crews',
      image: 'repair-crews.jpg',
      set: 'fleet-support',
      points: 4,
    },
    {
      id: 1297,
      title: 'Slicer Tools',
      image: 'slicer-tools.jpg',
      set: 'fleet-support',
      points: 7,
    },
  ],
  'fleet-command': [
    {
      id: 1390,
      title: 'All fighters, Follow Me!',
      image: 'all-fighters-follow-me.jpg',
      set: 'fleet-command',
      points: 5,
      unique: true,
    },
    {
      id: 1395,
      title: 'Entrapment Formation!',
      image: 'entrapment-formation.jpg',
      set: 'fleet-command',
      points: 5,
      unique: true,
    },
    {
      id: 1282,
      title: 'Intensify Firepower!',
      image: 'intensify-firepower.jpg',
      set: 'fleet-command',
      points: 6,
      unique: true,
    },
    {
      id: 1404,
      title: 'Shields to Maximum!',
      image: 'shields-to-maximum.jpg',
      set: 'fleet-command',
      points: 6,
      unique: true,
    },
    {
      id: 1404,
      title: 'Take Evasive Action!',
      image: 'take-evasive-action.jpg',
      set: 'fleet-command',
      points: 6,
      unique: true,
    },
  ],
  'support-team': [
    {
      id: 1088,
      title: 'Engine Techs',
      image: 'engine-techs.jpg',
      set: 'support-team',
      points: 8,
    },
    {
      id: 1089,
      title: 'Engineering Team',
      image: 'engineering-team.jpg',
      set: 'support-team',
      points: 5,
    },
    {
      id: 1316,
      title: 'Fighter Coordination Team',
      image: 'fighter-coordination-team.jpg',
      set: 'support-team',
      points: 3,
    },
    {
      id: 1317,
      title: 'Medical Team',
      image: 'medical-team.jpg',
      set: 'support-team',
      points: 1,
    },
    {
      id: 1090,
      title: 'Nav Team',
      image: 'nav-team.jpg',
      set: 'support-team',
      points: 4,
    },
    {
      id: 1262,
      title: 'Projection Experts',
      image: 'projection-experts.jpg',
      set: 'support-team',
      points: 6,
    },
  ],
  officer: [
    {
      id: 1075,
      title: 'Adar Tallon',
      image: 'adar-tallon.jpg',
      set: 'officer',
      points: 10,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1388,
      title: 'Ahsoka Tano',
      image: 'ahsoka-tano.jpg',
      set: 'officer',
      points: 2,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1015,
      title: 'Bail Organa',
      image: 'bail-organa.jpg',
      set: 'officer',
      points: 7,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1016,
      title: 'General Draven',
      image: 'general-draven.jpg',
      set: 'officer',
      points: 3,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1207,
      title: 'Lando Carissian',
      image: 'lando-calrissian.jpg',
      set: 'officer',
      points: 4,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1080,
      title: 'Leia Organa',
      image: 'leia-organa.jpg',
      set: 'officer',
      points: 3,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1398,
      title: 'Major Derlin',
      image: 'major-derlin.jpg',
      set: 'officer',
      points: 7,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1081,
      title: 'Ray Antilles',
      image: 'raymus-antilles.jpg',
      set: 'officer',
      points: 7,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1313,
      title: 'Toryn Farr',
      image: 'toryn-farr.jpg',
      set: 'officer',
      points: 7,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1208,
      title: 'Walex Blissex',
      image: 'walex-blissex.jpg',
      set: 'officer',
      points: 5,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1076,
      title: 'Admiral Chiraneau',
      image: 'admiral-chiraneau.jpg',
      set: 'officer',
      points: 10,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1205,
      title: 'Admiral Montferrat',
      image: 'admiral-montferrat.jpg',
      set: 'officer',
      points: 5,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1308,
      title: 'Admiral Titus',
      image: 'admiral-titus.jpg',
      set: 'officer',
      points: 2,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1307,
      title: 'Agent Kallus',
      image: 'agent-kallus.jpg',
      set: 'officer',
      points: 3,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1012,
      title: 'Captain Brunson',
      image: 'captain-brunson.jpg',
      set: 'officer',
      points: 5,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1206,
      title: 'Captain Needa',
      image: 'captain-needa.jpg',
      set: 'officer',
      points: 2,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1309,
      title: 'Commandant Aresko',
      image: 'commandant-aresko.jpg',
      set: 'officer',
      points: 7,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1309,
      title: 'Commander Gherant',
      image: 'commander-gherant.jpg',
      set: 'officer',
      points: 2,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1121209,
      title: 'Darth Vader',
      image: 'darth-vader.jpg',
      set: 'officer',
      points: 1,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1078,
      title: 'Director Isard',
      image: 'director-isard.jpg',
      set: 'officer',
      points: 3,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1072128,
      title: 'Director Krennic',
      image: 'director-krennic.jpg',
      set: 'officer',
      points: 8,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 107212128,
      title: 'Emperor Palpatine',
      image: 'emperor-palpatine.jpg',
      set: 'officer',
      points: 3,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1104,
      title: 'Governor Pryce',
      image: 'governor-pryce.jpg',
      set: 'officer',
      points: 7,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1014,
      title: 'Instructor Goran',
      image: 'instructor-goran.jpg',
      set: 'officer',
      points: 7,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1011212,
      title: 'Lira Wessex',
      image: 'lira-wessex.jpg',
      set: 'officer',
      points: 2,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1399,
      title: 'Minister Tua',
      image: 'minister-tua.jpg',
      set: 'officer',
      points: 2,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1008,
      title: 'Taskmaster Grint',
      image: 'taskmaster-grint.jpg',
      set: 'officer',
      points: 5,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 2672,
      title: 'The Grand Inquisitor',
      image: 'the-grand-inquisitor.jpg',
      set: 'officer',
      points: 4,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1084,
      title: 'Wulff Yularen',
      image: 'wulff-yularen.jpg',
      set: 'officer',
      points: 7,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 2791,
      title: 'Hondo Ohnaka',
      image: 'hondo-ohnaka.jpg',
      set: 'officer',
      points: 2,
      unique: true,
    },
    {
      id: 1017,
      title: 'Strategic Adviser',
      image: 'strategic-adviser.jpg',
      set: 'officer',
      points: 4,
      unique: true,
    },
    {
      id: 1311,
      title: 'Chart Officer',
      image: 'chart-officer.jpg',
      set: 'officer',
      points: 2,
    },
    {
      id: 1393,
      title: 'Damage Control Officer',
      image: 'damage-control-officer.jpg',
      set: 'officer',
      points: 5,
    },
    {
      id: 1077,
      title: 'Defense Liaison',
      image: 'defense-liaison.jpg',
      set: 'officer',
      points: 3,
    },
    {
      id: 1225,
      title: 'Engineering Captain',
      image: 'engineering-captain.jpg',
      set: 'officer',
      points: 6,
    },
    {
      id: 1310,
      title: 'Flight Commander',
      image: 'flight-commander.jpg',
      set: 'officer',
      points: 3,
    },
    {
      id: 1079,
      title: 'Intel Officer',
      image: 'intel-officer.jpg',
      set: 'officer',
      points: 7,
    },
    {
      id: 1228,
      title: 'Navigation Officer',
      image: 'navigation-officer.jpg',
      set: 'officer',
      points: 6,
    },
    {
      id: 1312,
      title: 'Skilled First Officer',
      image: 'skilled-first-officer.jpg',
      set: 'officer',
      points: 1,
    },
    {
      id: 1209,
      title: 'Support Officer',
      image: 'support-officer.jpg',
      set: 'officer',
      points: 4,
    },
    {
      id: 1227,
      title: 'Tactical Expert',
      image: 'tactical-expert.jpg',
      set: 'officer',
      points: 6,
    },
    {
      id: 1082,
      title: 'Veteran Captain',
      image: 'veteran-captain.jpg',
      set: 'officer',
      points: 3,
    },
    {
      id: 1083,
      title: 'Weapons Liaison',
      image: 'weapons-liaison.jpg',
      set: 'officer',
      points: 3,
    },
    {
      id: 1226,
      title: 'Wing Commander',
      image: 'wing-commander.jpg',
      set: 'officer',
      points: 6,
    },
  ],
  commander: [
    {
      id: 1178,
      title: 'Admiral Ackbar',
      image: 'admiral-ackbar.jpg',
      set: 'commander',
      points: 38,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1283,
      title: 'Admiral Raddus',
      image: 'admiral-raddus.jpg',
      set: 'commander',
      points: 26,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1392,
      title: 'Commander Sato',
      image: 'commander-sato.jpg',
      set: 'commander',
      points: 32,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1071,
      title: 'Garm Bel Iblis',
      image: 'garm-bel-iblis.jpg',
      set: 'commander',
      points: 25,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1305,
      title: 'General Cracken',
      image: 'general-cracken.jpg',
      set: 'commander',
      points: 26,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1072,
      title: 'General Dodonna',
      image: 'general-dodonna.jpg',
      set: 'commander',
      points: 20,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1306,
      title: 'General Madine',
      image: 'general_madine.jpg',
      set: 'commander',
      points: 30,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1181,
      title: 'General Rieekan',
      image: 'general-rieekan.jpg',
      set: 'commander',
      points: 30,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 2785,
      title: 'Leia Organa',
      image: 'swm27-leia-organa.jpg',
      set: 'commander',
      points: 38,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1074,
      title: 'Mon Mothma',
      image: 'mon-mothma.jpg',
      set: 'commander',
      points: 30,
      faction: 'rebel',
      unique: true,
    },
    {
      id: 1304,
      title: 'Admiral Konstantine',
      image: 'admiral-konstantine.jpg',
      set: 'commander',
      points: 23,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1069,
      title: 'Admiral Motti',
      image: 'admiral-motti.jpg',
      set: 'commander',
      points: 24,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1179,
      title: 'Admiral Ozzel',
      image: 'admiral-ozzel.jpg',
      set: 'commander',
      points: 20,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1179,
      title: 'Admiral Piett',
      image: 'admiral-piett.jpg',
      set: 'commander',
      points: 22,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1070,
      title: 'Admiral Screed',
      image: 'admiral-screed.jpg',
      set: 'commander',
      points: 26,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 2670,
      title: 'Admiral Sloane',
      image: 'admiral-sloane.jpg',
      set: 'commander',
      points: 24,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1180,
      title: 'Darth Vader',
      image: 'darth-vader-commander.jpg',
      set: 'commander',
      points: 36,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1182,
      title: 'Emperor Palpatine',
      image: 'palpatine.jpg',
      set: 'commander',
      points: 35,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1303,
      title: 'General Tagge',
      image: 'general-tagge.jpg',
      set: 'commander',
      points: 25,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1284,
      title: 'Grand Admiral Thrawn',
      image: 'grand-admiral-thrawn.jpg',
      set: 'commander',
      points: 32,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1073,
      title: 'Grand Moff Tarkin',
      image: 'tarkin.jpg',
      set: 'commander',
      points: 38,
      faction: 'imperial',
      unique: true,
    },
    {
      id: 1400,
      title: 'Moff Jerjerrod',
      image: 'moff-jerjerrod.jpg',
      set: 'commander',
      points: 23,
      faction: 'imperial',
      unique: true,
    },
  ],
}

const objectiveCards: ObjectiveCard[] = [
  {
    id: 1152,
    title: 'Dangerous Territory',
    image: 'dangerous-territory.jpg',
    set: 'navigation',
  },
  {
    id: 1153,
    title: 'Intel Sweep',
    image: 'intel-sweep.jpg',
    set: 'navigation',
  },
  {
    id: 1154,
    title: 'Minefields',
    image: 'minefields.jpg',
    set: 'navigation',
  },
  {
    id: 1380,
    title: 'Navigational Hazards',
    image: 'navigational-hazards.jpg',
    set: 'navigation',
  },
  {
    id: 1381,
    title: 'Salvage Run',
    image: 'salvage-run.jpg',
    set: 'navigation',
  },
  {
    id: 1382,
    title: 'Sensor Net',
    image: 'sensor-net.jpg',
    set: 'navigation',
  },
  {
    id: 1383,
    title: 'Solar Corona',
    image: 'solar-corona.jpg',
    set: 'navigation',
  },
  {
    id: 1155,
    title: 'Superior Positions',
    image: 'superior-positions.jpg',
    set: 'navigation',
  },
  {
    id: 1387,
    title: 'Capture the VIP',
    image: 'capture-the-vip.jpg',
    set: 'defense',
  },
  {
    id: 1148,
    title: 'Contested Outpost',
    image: 'contested-outpost.jpg',
    set: 'defense',
  },
  {
    id: 1384,
    title: 'Fighter Ambush',
    image: 'fighter-ambush.jpg',
    set: 'defense',
  },
  {
    id: 1149,
    title: 'Fire Lanes',
    image: 'fire-lanes.jpg',
    set: 'defense',
  },
  {
    id: 1150,
    title: 'Fleet Ambush',
    image: 'fleet-ambush.jpg',
    set: 'defense',
  },
  {
    id: 1151,
    title: 'Hyperspace Assault',
    image: 'hyperspace-assault.jpg',
    set: 'defense',
  },
  {
    id: 1385,
    title: 'Jamming Barrier',
    image: 'jamming-barrier.jpg',
    set: 'defense',
  },
  {
    id: 1386,
    title: 'Planetary Ion Cannon',
    image: 'planetary-ion-cannon.jpg',
    set: 'defense',
  },
  {
    id: 1144,
    title: 'Advanced Gunnery',
    image: 'advanced-gunnery.jpg',
    set: 'assault',
  },
  {
    id: 1376,
    title: 'Blockade Run',
    image: 'blockade-run.jpg',
    set: 'assault',
  },
  {
    id: 1377,
    title: 'Close-Range Intel Scan',
    image: 'close-range-intel-scan.jpg',
    set: 'assault',
  },
  {
    id: 1145,
    title: 'Most Wanted',
    image: 'most-wanted.jpg',
    set: 'assault',
  },
  {
    id: 1146,
    title: 'Opening Salvo',
    image: 'opening-salvo.jpg',
    set: 'assault',
  },
  {
    id: 1147,
    title: 'Precision Strike',
    image: 'precision-strike.jpg',
    set: 'assault',
  },
  {
    id: 1378,
    title: 'Station Assault',
    image: 'station-assault.jpg',
    set: 'assault',
  },
  {
    id: 1379,
    title: 'Targeting Beacons',
    image: 'targeting-beacons.jpg',
    set: 'assault',
  },
]

const imperialShipCards: Ship[] = [
  {
    id: 1330,
    title: 'Arquitens Command \nCruiser',
    image: 'arquitens-class-command-cruiser.jpg',
    set: 'ship',
    type: 'arquitens',
    points: 59,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'defensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1331,
    title: 'Arquitens Light Cruiser',
    image: 'arquitens-class-light-cruiser.jpg',
    set: 'ship',
    type: 'arquitens',
    points: 54,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'defensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1049,
    title: 'Gladiator I',
    image: 'gladiator-i.jpg',
    set: 'ship',
    type: 'gladiator-class-star-destroyer',
    points: 56,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'support-team': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1050,
    title: 'Gladiator II',
    image: 'gladiator-ii.jpg',
    set: 'ship',
    type: 'gladiator-class-star-destroyer',
    points: 62,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'support-team': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1291,
    title: 'Gozanti Assault Carriers',
    image: 'gozanti-class-assault-carriers.jpg',
    set: 'ship',
    type: 'gozanti',
    points: 28,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      officer: null,
      'fleet-support': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
  {
    id: 1290,
    title: 'Gozanti Cruisers',
    image: 'gozanti-class-cruisers.jpg',
    set: 'ship',
    type: 'gozanti',
    points: 23,
    faction: 'imperial',
    size: 'small',
    dual: false,
    upgrades: {
      officer: null,
      'fleet-support': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
  {
    id: 1203,
    title: 'Imperial I',
    image: 'imperial-i-class-star-destroyer.jpg',
    set: 'ship',
    type: 'imperial-class-star-destroyer',
    points: 110,
    faction: 'imperial',
    size: 'large',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'offensive-retrofit-2': null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1204,
    title: 'Imperial II',
    image: 'imperial-ii-class-star-destroyer.jpg',
    set: 'ship',
    type: 'imperial-class-star-destroyer',
    points: 120,
    faction: 'imperial',
    size: 'large',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1278,
    title: 'ISD Cymoon 1 Refit',
    image: 'isd-cymoon-1-refit.jpg',
    set: 'ship',
    type: 'imperial-class-star-destroyer',
    points: 112,
    faction: 'imperial',
    size: 'large',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'fleet-command': null,
      'weapons-team': null,
      'offensive-retrofit': null,
      turbolasers: null,
      'turbolasers-2': null,
      title: null,
    },
  },
  {
    id: 1279,
    title: 'ISD Kuat Refit',
    image: 'isd-kuat-refit.jpg',
    set: 'ship',
    type: 'imperial-class-star-destroyer',
    points: 112,
    faction: 'imperial',
    size: 'large',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      'ion-cannons': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1293,
    title: 'Interdictor Combat Refit',
    image: 'nterdictor-combat-refit.jpg',
    set: 'ship',
    type: 'interdictor',
    points: 93,
    faction: 'imperial',
    size: 'medium',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'offensive-retrofit': null,
      'experimental-retrofit': null,
      'ion-cannons': null,
      title: null,
    },
  },
  {
    id: 1292,
    title: 'Interdictor Suppression Refit',
    image: 'interdictor-suppression-refit.jpg',
    set: 'ship',
    type: 'interdictor',
    points: 90,
    faction: 'imperial',
    size: 'medium',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'offensive-retrofit': null,
      'experimental-retrofit': null,
      'experimental-retrofit-2': null,
      'ion-cannons': null,
      title: null,
    },
  },
  {
    id: 2666,
    title: 'Quasar Fire I',
    image: 'quasar-fire-i-class-cruiser-carrier.jpg',
    set: 'ship',
    type: 'quasar',
    points: 54,
    faction: 'imperial',
    size: 'medium',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'offensive-retrofit-2': null,
      title: null,
    },
  },
  {
    id: 2664,
    title: 'Quasar Fire II',
    image: 'quasar-fire-ii-class-cruiser-carrier.jpg',
    set: 'ship',
    type: 'quasar',
    points: 61,
    faction: 'imperial',
    size: 'medium',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'weapons-team-2': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
  {
    id: 1201,
    title: 'Raider I',
    image: 'raider-i-class-corvette.jpg',
    set: 'ship',
    type: 'raider-class-corvette',
    points: 44,
    faction: 'imperial',
    size: 'small',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1202,
    title: 'Raider II',
    image: 'raider-ii-class-corvette.jpg',
    set: 'ship',
    type: 'raider-class-corvette',
    points: 48,
    faction: 'imperial',
    size: 'small',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'ion-cannons': null,
      title: null,
    },
  },
  {
    id: 1051,
    title: 'Victory I',
    image: 'victory-i.jpg',
    set: 'ship',
    type: 'victory-class-star-destroyer',
    points: 73,
    faction: 'imperial',
    size: 'medium',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      turbolasers: null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1052,
    title: 'Victory II',
    image: 'victory-ii.jpg',
    set: 'ship',
    type: 'victory-class-star-destroyer',
    points: 85,
    faction: 'imperial',
    size: 'medium',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      turbolasers: null,
      'ion-cannons': null,
      title: null,
    },
  },
  {
    id: 1053,
    title: 'SSD Command Prototype',
    image: 'ssd-command-prototype.jpg',
    set: 'ship',
    type: 'super-star-destroyer',
    points: 220,
    faction: 'imperial',
    size: 'huge',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'officer-2': null,
      'officer-3': null,
      'weapons-team': null,
      'fleet-command': null,
      'fleet-command-2': null,
      'offensive-retrofit': null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
]

const rebelShipCards: Ship[] = [
  {
    id: 1043,
    title: 'Assault Frigate Mk2 A',
    image: 'assault-frigate-mark-ii-a.jpg',
    set: 'ship',
    type: 'assault-frigate',
    points: 81,
    faction: 'rebel',
    size: 'medium',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1044,
    title: 'Assault Frigate Mk2 B',
    image: 'assault-frigate-mark-ii-b.jpg',
    set: 'ship',
    type: 'assault-frigate',
    points: 72,
    faction: 'rebel',
    size: 'medium',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1045,
    title: 'CR90 Corvette A',
    image: 'cr90-corvette-a.jpg',
    set: 'ship',
    type: 'corvette',
    points: 44,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'defensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1046,
    title: 'CR90 Corvette B',
    image: 'cr90-corvette-b.jpg',
    set: 'ship',
    type: 'corvette',
    points: 39,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'defensive-retrofit': null,
      'ion-cannons': null,
      title: null,
    },
  },
  {
    id: 1277,
    title: 'GR-75 Combat Retrofits',
    image: 'swm19-gr-75-combat-retrofits.jpg',
    set: 'ship',
    type: 'gr-75',
    points: 24,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      officer: null,
      'fleet-support': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
  {
    id: 1276,
    title: 'GR-75 Medium Transports',
    image: 'swm19-gr-75-medium-transports.jpg',
    set: 'ship',
    type: 'gr-75',
    points: 18,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      officer: null,
      'fleet-support': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
  {
    id: 2783,
    title: 'Hammerhead Scout Corvette',
    image: 'swm27-hammerhead-scout-corvette.jpg',
    set: 'ship',
    type: 'hammerhead',
    points: 41,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 2781,
    title: 'Hammerhead Torpedo Corvette',
    image: 'swm27-hammerhead-torpedo-corvette.jpg',
    set: 'ship',
    type: 'hammerhead',
    points: 36,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1186,
    title: 'MC30c Scout Frigate',
    image: 'mc30c-scout-frigate.jpg',
    set: 'ship',
    type: 'mc30c-frigate',
    points: 69,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'defensive-retrofit': null,
      ordnance: null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1187,
    title: 'MC30c Torpedo Frigate',
    image: 'mc30c-torpedo-frigate.jpg',
    set: 'ship',
    type: 'mc30c-frigate',
    points: 63,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'defensive-retrofit': null,
      ordnance: null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1002,
    title: 'MC75 Armored Cruiser',
    image: 'mc75-armored-cruiser.jpg',
    set: 'ship',
    type: 'mc75-cruiser',
    points: 104,
    faction: 'rebel',
    size: 'large',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      ordnance: null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1003,
    title: 'MC75 Ordnance Cruiser',
    image: 'mc75-ordnance-cruiser.jpg',
    set: 'ship',
    type: 'mc75-cruiser',
    points: 100,
    faction: 'rebel',
    size: 'large',
    dual: true,
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      ordnance: null,
      'ordnance-2': null,
      title: null,
    },
  },
  {
    id: 1188,
    title: 'MC80 Assault Cruiser',
    image: 'mc80-assault-cruiser.jpg',
    set: 'ship',
    type: 'mc80-cruiser',
    points: 114,
    faction: 'rebel',
    size: 'large',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'defensive-retrofit': null,
      'defensive-retrofit-2': null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1189,
    title: 'MC80 Command Cruiser',
    image: 'mc80-command-cruiser.jpg',
    set: 'ship',
    type: 'mc80-cruiser',
    points: 106,
    faction: 'rebel',
    size: 'large',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'offensive-retrofit': null,
      'defensive-retrofit': null,
      'ion-cannons': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1275,
    title: 'MC80 Battle Cruiser',
    image: 'swm17-mc80-battle-cruiser.jpg',
    set: 'ship',
    type: 'mc80-liberty',
    points: 103,
    faction: 'rebel',
    size: 'large',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'support-team': null,
      'ion-cannons': null,
      turbolasers: null,
      'turbolasers-2': null,
      title: null,
    },
  },
  {
    id: 1274,
    title: 'MC80 Star Cruiser',
    image: 'swm17-mc80-star-cruiser.jpg',
    set: 'ship',
    type: 'mc80-liberty',
    points: 96,
    faction: 'rebel',
    size: 'large',
    upgrades: {
      commander: null,
      officer: null,
      'weapons-team': null,
      'support-team': null,
      'ion-cannons': null,
      turbolasers: null,
      'turbolasers-2': null,
      title: null,
    },
  },
  {
    id: 1047,
    title: 'Nebulon-B Escort Frigate',
    image: 'nebulon-b-escort-frigate.jpg',
    set: 'ship',
    type: 'nebulon-b',
    points: 57,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1048,
    title: 'Nebulon-B Support Refit',
    image: 'nebulon-b-support-refit.jpg',
    set: 'ship',
    type: 'nebulon-b',
    points: 51,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      turbolasers: null,
      title: null,
    },
  },
  {
    id: 1334,
    title: 'Pelta Assault Ship',
    image: 'pelta-class-assault-ship.jpg',
    set: 'ship',
    type: 'pelta',
    points: 56,
    faction: 'rebel',
    size: 'small',
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'fleet-command': null,
      ordnance: null,
      title: null,
    },
  },
  {
    id: 1335,
    title: 'Pelta Command Ship',
    image: 'pelta-class-command-ship.jpg',
    set: 'ship',
    type: 'pelta',
    points: 60,
    faction: 'rebel',
    size: 'small',
    dual: false,
    upgrades: {
      commander: null,
      officer: null,
      'support-team': null,
      'fleet-command': null,
      'offensive-retrofit': null,
      title: null,
    },
  },
]

const squadronCards = [
  {
    id: 1345,
    title: 'Biggs Darklighter',
    image: 'biggs-darklighter.jpg',
    set: 'squadron',
    type: 'x-wing',
    points: 19,
    faction: 'rebel',
    keywords: ['bomber', 'escort'],
    unique: true,
  },
  {
    id: 1351,
    title: 'Corran Horn',
    image: 'corran-horn.jpg',
    set: 'squadron',
    type: 'e-wing',
    points: 22,
    faction: 'rebel',
    keywords: ['bomber', 'rogue', 'snipe'],
    unique: true,
  },
  {
    id: 1352,
    title: 'Dagger Squadron',
    image: 'dagger-squadron.jpg',
    set: 'squadron',
    type: 'b-wing',
    points: 15,
    faction: 'rebel',
    keywords: ['bomber', 'swarm'],
    unique: true,
  },
  {
    id: 1260,
    title: 'Dash Rendar',
    image: 'dash-rendar.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 24,
    faction: 'rebel',
    keywords: ['bomber', 'rogue'],
    unique: true,
  },
  {
    id: 1133,
    title: 'Dutch Vander',
    image: 'dutchvander.jpg',
    set: 'squadron',
    type: 'y-wing',
    points: 16,
    faction: 'rebel',
    keywords: ['bomber', 'heavy'],
    unique: true,
  },
  {
    id: 1355,
    title: 'Gold Squadron',
    image: 'gold-squadron.jpg',
    set: 'squadron',
    type: 'y-wing',
    points: 12,
    faction: 'rebel',
    keywords: ['bomber'],
    unique: true,
  },
  {
    id: 1356,
    title: 'Green Squadron',
    image: 'green-squadron.jpg',
    set: 'squadron',
    type: 'a-wing',
    points: 12,
    faction: 'rebel',
    keywords: ['bomber', 'counter'],
    unique: true,
  },
  {
    id: 1258,
    title: 'Han Solo',
    image: 'han-solo.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 26,
    faction: 'rebel',
    keywords: ['grit', 'rogue'],
    unique: true,
  },
  {
    id: 1357,
    title: 'Hera Syndulla',
    image: 'hera-syndulla.jpg',
    set: 'squadron',
    type: 'vcx-100-freighter',
    points: 28,
    faction: 'rebel',
    keywords: ['grit', 'rogue'],
    unique: true,
  },
  {
    id: 1259,
    title: 'Jan Ors',
    image: 'jan-ors.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 19,
    faction: 'rebel',
    keywords: ['counter', 'intel'],
    unique: true,
  },
  {
    id: 1358,
    title: 'Ketsu Onyo',
    image: 'ketsu-onyo.jpg',
    set: 'squadron',
    type: 'lancer-pursuit-craft',
    points: 22,
    faction: 'rebel',
    keywords: ['bomber', 'grit', 'rogue'],
    unique: true,
  },
  {
    id: 1134,
    title: 'Keyan Farlander',
    image: 'keyanfarlander.jpg',
    set: 'squadron',
    type: 'b-wing',
    points: 20,
    faction: 'rebel',
    keywords: ['bomber'],
    unique: true,
  },
  {
    id: 1347,
    title: 'Lieutenant Blount',
    image: 'lieutenant-blount.jpg',
    set: 'squadron',
    type: 'z-95',
    points: 14,
    faction: 'rebel',
    keywords: ['swarm'],
    unique: true,
  },
  {
    id: 1135,
    title: 'Luke Skywalker',
    image: 'luke-skywalker.jpg',
    set: 'squadron',
    type: 'x-wing',
    points: 20,
    faction: 'rebel',
    keywords: ['bomber', 'escort'],
    unique: true,
  },
  {
    id: 1405,
    title: 'Norra Wexley',
    image: 'norra-wexley.jpg',
    set: 'squadron',
    type: 'y-wing',
    points: 17,
    faction: 'rebel',
    keywords: ['bomber'],
    unique: true,
  },
  {
    id: 1261,
    title: 'Nym',
    image: 'nym.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 21,
    faction: 'rebel',
    keywords: ['bomber', 'grit'],
    unique: true,
  },
  {
    id: 1363,
    title: 'Rogue Squadron',
    image: 'rogue-squadron.jpg',
    set: 'squadron',
    type: 'x-wing',
    points: 14,
    faction: 'rebel',
    keywords: ['bomber', 'rogue'],
    unique: true,
  },
  {
    id: 1365,
    title: 'Shara Bey',
    image: 'shara-bey.jpg',
    set: 'squadron',
    type: 'a-wing',
    points: 17,
    faction: 'rebel',
    keywords: ['counter'],
    unique: true,
  },
  {
    id: 1367,
    title: 'Ten Numb',
    image: 'ten-numb.jpg',
    set: 'squadron',
    type: 'b-wing',
    points: 19,
    faction: 'rebel',
    keywords: ['bomber'],
    unique: true,
  },
  {
    id: 1136,
    title: 'Tycho Celchu',
    image: 'tycho.jpg',
    set: 'squadron',
    type: 'a-wing',
    points: 16,
    faction: 'rebel',
    keywords: ['counter'],
    unique: true,
  },
  {
    id: 1137,
    title: 'Wedge Antilles',
    image: 'wedgeantilles.jpg',
    set: 'squadron',
    type: 'x-wing',
    points: 19,
    faction: 'rebel',
    keywords: ['bomber', 'escort'],
    unique: true,
  },
  {
    id: 1122,
    title: 'TIE Fighter Squadron',
    image: 'tie-fighter-squadron.jpg',
    set: 'squadron',
    type: 'tie-fighter',
    points: 8,
    faction: 'imperial',
    keywords: ['swarm'],
  },
  {
    id: 1125,
    title: 'Howlrunner',
    image: 'howlrunner.jpg',
    set: 'squadron',
    type: 'tie-fighter',
    points: 16,
    faction: 'imperial',
    keywords: ['swarm'],
    unique: true,
  },
  {
    id: 1370,
    title: 'Valen Rudor',
    image: 'valen-rudor.jpg',
    set: 'squadron',
    type: 'tie-fighter',
    points: 13,
    faction: 'imperial',
    keywords: ['swarm'],
    unique: true,
  },
  {
    id: 1127,
    title: 'Mauler Mithel',
    image: 'mauler-mithel.jpg',
    set: 'squadron',
    type: 'tie-fighter',
    points: 15,
    faction: 'imperial',
    keywords: ['swarm'],
    unique: true,
  },
  {
    id: 1346,
    title: 'Black Squadron',
    image: 'black-squadron.jpg',
    set: 'squadron',
    type: 'tie-fighter',
    points: 9,
    faction: 'imperial',
    keywords: ['counter', 'escort'],
    unique: true,
  },
  {
    id: 1128,
    title: 'TIE Interceptor',
    image: 'tie-interceptor-squadron.jpg',
    set: 'squadron',
    type: 'tie-interceptor',
    points: 11,
    faction: 'imperial',
    keywords: ['swarm', 'counter'],
    unique: false,
  },
  {
    id: 1128,
    title: 'Soontir Fel',
    image: 'soontir-fel.jpg',
    set: 'squadron',
    type: 'tie-interceptor',
    points: 18,
    faction: 'imperial',
    keywords: ['counter', 'swarm'],
    unique: true,
  },
  {
    id: 1349,
    title: 'Ciena Ree',
    image: 'ciena-ree.jpg',
    set: 'squadron',
    type: 'tie-interceptor',
    points: 17,
    faction: 'imperial',
    keywords: ['counter', 'swarm'],
    unique: true,
  },
  {
    id: 1364,
    title: 'Saber Squadron',
    image: 'saber-squadron.jpg',
    set: 'squadron',
    type: 'tie-interceptor',
    points: 12,
    faction: 'imperial',
    keywords: ['snipe', 'swarm'],
    unique: true,
  },
  {
    id: 1253,
    title: 'Boba Fett',
    image: 'bobafett.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 26,
    faction: 'imperial',
    keywords: ['bomber', 'rogue'],
    unique: true,
  },
  {
    id: 1257,
    title: 'Bossk',
    image: 'bossk.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 23,
    faction: 'imperial',
    keywords: ['grit', 'rogue'],
    unique: true,
  },
  {
    id: 1348,
    title: 'Captain Jonus',
    image: 'captain-jonus.jpg',
    set: 'squadron',
    type: 'tie-bomber',
    points: 16,
    faction: 'imperial',
    keywords: ['bomber', 'grit', 'heavy'],
    unique: true,
  },
  {
    id: 1350,
    title: 'Colonel Jendon',
    image: 'colonel-jendon.jpg',
    set: 'squadron',
    type: 'lambda-shuttle',
    points: 20,
    faction: 'imperial',
    keywords: ['heavy', 'relay'],
    unique: true,
  },
  {
    id: 1124,
    title: 'Darth Vader',
    image: 'darth-vader.jpg',
    set: 'squadron',
    type: 'tie-advanced',
    points: 21,
    faction: 'imperial',
    keywords: ['escort'],
    unique: true,
  },
  {
    id: 1255,
    title: 'Dengar',
    image: 'dengar.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 20,
    faction: 'imperial',
    keywords: ['intel', 'swarm'],
    unique: true,
  },
  {
    id: 1354,
    title: 'Gamma Squadron',
    image: 'gamma-squadron.jpg',
    set: 'squadron',
    type: 'tie-bomber',
    points: 10,
    faction: 'imperial',
    keywords: ['bomber', 'grit'],
    unique: true,
  },
  {
    id: 1022,
    title: 'Gar Saxon',
    image: 'gar-saxon.jpg',
    set: 'squadron',
    type: 'mandalorian-gauntlet-fighter',
    points: 23,
    faction: 'imperial',
    keywords: ['assault', 'rogue'],
    unique: true,
  },

  {
    id: 1254,
    title: 'IG-88',
    image: 'ig88.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 21,
    faction: 'imperial',
    keywords: ['counter', 'rogue'],
    unique: true,
  },
  {
    id: 1361,
    title: 'Maarek Stele',
    image: 'maarek-stele.jpg',
    set: 'squadron',
    type: 'tie-defender',
    points: 21,
    faction: 'imperial',
    keywords: ['bomber', 'grit'],
    unique: true,
  },
  {
    id: 1126,
    title: 'Major Rhymer',
    image: 'major-rhymer.jpg',
    set: 'squadron',
    type: 'tie-bomber',
    points: 16,
    faction: 'imperial',
    keywords: ['bomber', 'heavy'],
    unique: true,
  },

  {
    id: 1362,
    title: 'Morna Kee',
    image: 'morna-kee.jpg',
    set: 'squadron',
    type: 'vt-49-decimator',
    points: 27,
    faction: 'imperial',
    keywords: ['counter', 'rogue'],
    unique: true,
  },

  {
    id: 1366,
    title: 'Tempest Squadron',
    image: 'tempest-squadron.jpg',
    set: 'squadron',
    type: 'tie-advanced',
    points: 13,
    faction: 'imperial',
    keywords: ['bomber', 'escort'],
    unique: true,
  },

  {
    id: 1373,
    title: 'Whisper',
    image: 'whisper.jpg',
    set: 'squadron',
    type: 'tie-phantom',
    points: 20,
    faction: 'imperial',
    keywords: ['cloak'],
    unique: true,
  },
  {
    id: 1375,
    title: 'Zertik Strom',
    image: 'zertik-strom.jpg',
    set: 'squadron',
    type: 'tie-advanced',
    points: 15,
    faction: 'imperial',
    keywords: ['escort'],
    unique: true,
  },
  {
    divider: true,
  },
  {
    id: 1129,
    title: 'A-wing Squadron',
    image: 'awingsquadron.jpg',
    set: 'squadron',
    type: 'a-wing',
    points: 11,
    faction: 'rebel',
    keywords: ['counter'],
  },
  {
    id: 1130,
    title: 'B-wing Squadron',
    image: 'bwingsquadron.jpg',
    set: 'squadron',
    type: 'b-wing',
    points: 14,
    faction: 'rebel',
    keywords: ['bomber'],
  },
  {
    id: 1353,
    title: 'E-wing Squadron',
    image: 'e-wing-squadron.jpg',
    set: 'squadron',
    type: 'e-wing',
    points: 15,
    faction: 'rebel',
    keywords: ['bomber', 'snipe'],
  },
  {
    id: 1267,
    title: 'HWK-290',
    image: 'hwk-290.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 12,
    faction: 'rebel',
    keywords: ['counter', 'intel'],
  },
  {
    id: 1360,
    title: 'Lancer Pursuit Craft',
    image: 'lancer-class-pursuit-craft.jpg',
    set: 'squadron',
    type: 'lancer-pursuit-craft',
    points: 15,
    faction: 'rebel',
    keywords: ['bomber', 'grit', 'rogue'],
  },
  {
    id: 1268,
    title: 'Scurrg H-6 Bomber',
    image: 'scurrg-h6.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 16,
    faction: 'rebel',
    keywords: ['bomber', 'grit', 'heavy'],
  },
  {
    id: 1371,
    title: 'VCX-100 Freighter',
    image: 'vcx-100-freighter.jpg',
    set: 'squadron',
    type: 'vcx-100-freighter',
    points: 15,
    faction: 'rebel',
    keywords: ['heavy', 'relay', 'strategic'],
  },
  {
    id: 1131,
    title: 'X-wing Squadron',
    image: 'xwing-squadron.jpg',
    set: 'squadron',
    type: 'x-wing',
    points: 13,
    faction: 'rebel',
    keywords: ['bomber', 'escort'],
  },
  {
    id: 1132,
    title: 'Y-wing Squadron',
    image: 'ywingsquadron.jpg',
    set: 'squadron',
    type: 'y-wing',
    points: 10,
    faction: 'rebel',
    keywords: ['bomber', 'heavy'],
  },
  {
    id: 1265,
    title: 'YT-1300',
    image: 'yt-1300.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 13,
    faction: 'rebel',
    keywords: ['counter', 'escort'],
  },
  {
    id: 1266,
    title: 'YT-2400',
    image: 'yt-2400.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 16,
    faction: 'rebel',
    keywords: ['rogue'],
  },
  {
    id: 1374,
    title: 'Z-95 Headhunter Squadron',
    image: 'z-95-headhunter-squadron.jpg',
    set: 'squadron',
    type: 'z-95',
    points: 7,
    faction: 'rebel',
    keywords: ['swarm'],
  },
  {
    id: 1270,
    title: 'Aggressor Assault Fighter',
    image: 'aggressor.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 16,
    faction: 'imperial',
    keywords: ['counter', 'rogue'],
  },
  {
    id: 1242,
    title: 'Firespray-31',
    image: 'firespray.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 18,
    faction: 'imperial',
    keywords: ['bomber', 'rogue'],
  },
  {
    id: 1271,
    title: 'JumpMaster 5000',
    image: 'jumpmaster-5000.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 12,
    faction: 'imperial',
    keywords: ['intel', 'swarm'],
  },
  {
    id: 1359,
    title: 'Lambda Shuttle',
    image: 'lambda-class-shuttle.jpg',
    set: 'squadron',
    type: 'lambda-shuttle',
    points: 15,
    faction: 'imperial',
    keywords: ['heavy', 'relay', 'strategic'],
  },
  {
    id: 1009,
    title: 'Mandalorian Gauntlet Fighter',
    image: 'mandalorian-gauntlet-fighter.jpg',
    set: 'squadron',
    type: 'mandalorian-gauntlet-fighter',
    points: 20,
    faction: 'imperial',
    keywords: ['assault', 'rogue'],
  },

  {
    id: 1121,
    title: 'TIE Bomber Squadron',
    image: 'tie-bomber-squadron.jpg',
    set: 'squadron',
    type: 'tie-bomber',
    points: 9,
    faction: 'imperial',
    keywords: ['bomber', 'heavy'],
  },
  {
    id: 1120,
    title: 'TIE Advanced Squadron',
    image: 'tie-advanced-squadron.jpg',
    set: 'squadron',
    type: 'tie-advanced',
    points: 12,
    faction: 'imperial',
    keywords: ['escort'],
  },
  {
    id: 1368,
    title: 'TIE Defender Squadron',
    image: 'tie-defender-squadron.jpg',
    set: 'squadron',
    type: 'tie-defender',
    points: 16,
    faction: 'imperial',
    keywords: ['bomber'],
  },
  {
    id: 1369,
    title: 'TIE Phantom Squadron',
    image: 'tie-phantom-squadron.jpg',
    set: 'squadron',
    type: 'tie-phantom',
    points: 14,
    faction: 'imperial',
    keywords: ['cloak'],
  },
  {
    id: 1372,
    title: 'VT-49 Decimator',
    image: 'vt-49-decimator.jpg',
    set: 'squadron',
    type: 'vt-49-decimator',
    points: 22,
    faction: 'imperial',
    keywords: ['counter', 'heavy', 'rogue'],
  },
  {
    id: 1269,
    title: 'YV-666',
    image: 'yv-666.jpg',
    set: 'squadron',
    type: 'rogue-villain',
    points: 15,
    faction: 'imperial',
    keywords: ['grit', 'heavy', 'rogue'],
  },
]

export { upgradeCards, imperialShipCards, rebelShipCards, squadronCards, objectiveCards }
